#!/usr/bin/with-contenv bash

mkdir -p \
    /etc/nginx/site-confs \
    /etc/nginx/conf.d \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx \
    /etc/ssl/certs \
    /etc/ssl/private

if [[ -z "$NGINX_RESOLVER" ]]; then
    IP_LIST=""
    while read -r line; do
        if [[ $line =~ ^nameserver.* ]]; then
            IP=$(echo $line | cut -d" " -f2)
            COLONS=$(echo $IP | tr -dc ":" | awk '{ print length }')
            if [[ $COLONS -ge 2 ]]; then
                IP="[$IP]"
            fi
            if [[ ! "$IP_LIST" = "" ]]; then
                IP_LIST+=" "
            fi
            IP_LIST+="$IP"
        fi
    done < <(cat /etc/resolv.conf)
    export NGINX_RESOLVER=$IP_LIST
fi

echo "Using Nginx resolver: =$NGINX_RESOLVER="

# Явно экспортируем HTTPS_PORT
export HTTPS_PORT=${HTTPS_PORT:-8443}

# Генерация самоподписанного сертификата с нужными именами
if [ ! -f /etc/ssl/certs/fullchain.pem ] || [ ! -f /etc/ssl/private/privkey.pem ]; then
    echo "Generating self-signed SSL certificate..."
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/private/privkey.pem \
        -out /etc/ssl/certs/fullchain.pem \
        -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=${XMPP_DOMAIN:-localhost}"
fi

# colibri-ws settings
COLIBRI_WEBSOCKET_UNSAFE_REGEX="[a-zA-Z0-9-\._]+"
if [ -z "$COLIBRI_WEBSOCKET_REGEX" ]; then
    if [[ "$ENABLE_COLIBRI_WEBSOCKET_UNSAFE_REGEX" == "1" ]]; then
        export COLIBRI_WEBSOCKET_REGEX="$COLIBRI_WEBSOCKET_UNSAFE_REGEX"
    else
        [ -z "$COLIBRI_WEBSOCKET_JVB_LOOKUP_NAME" ] && export COLIBRI_WEBSOCKET_JVB_LOOKUP_NAME="jvb"
        if [[ "$DISABLE_COLIBRI_WEBSOCKET_JVB_LOOKUP" == "1" ]]; then
            echo "WARNING: DISABLE_COLIBRI_WEBSOCKET_JVB_LOOKUP is set and no value for COLIBRI_WEBSOCKET_REGEX was provided, using static value 'jvb' for COLIBRI_WEBSOCKET_REGEX"
        else
            export COLIBRI_WEBSOCKET_REGEX="$(dig +short +search $COLIBRI_WEBSOCKET_JVB_LOOKUP_NAME)"
        fi
    fi
fi

[ -z "${XMPP_HIDDEN_DOMAIN}" ] && export XMPP_HIDDEN_DOMAIN="$XMPP_RECORDER_DOMAIN"

tpl /defaults/nginx.conf > /etc/nginx/nginx.conf
tpl /defaults/ssl.conf > /etc/nginx/conf.d/ssl.conf

# Всегда используем шаблон /defaults/default, игнорируя локальный файл
tpl /defaults/default > /etc/nginx/sites-enabled/default

# Убираем запись в config.js напрямую
if [[ -f /config/custom-config.js ]]; then
    cat /config/custom-config.js >> /usr/share/jitsi-meet/config.js
fi

cp /defaults/interface_config.js /usr/share/jitsi-meet/interface_config.js
if [[ -f /config/custom-interface_config.js ]]; then
    cat /config/custom-interface_config.js >> /usr/share/jitsi-meet/interface_config.js
fi
