#!/usr/bin/with-contenv bash

if [[ -z $JVB_DISABLE_XMPP ]]; then
    if [[ -z $JVB_AUTH_PASSWORD ]]; then
        echo 'FATAL ERROR: JVB auth password must be set'
        exit 1
    fi

    OLD_JVB_AUTH_PASSWORD=passw0rd
    if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
        echo 'FATAL ERROR: JVB auth password must be changed, check the README'
        exit 1
    fi

    # Указываем Prosody как XMPP-сервер
    [ -z "${XMPP_SERVER}" ] && export XMPP_SERVER="prosody"

    # Локальный IP для ICE
    export LOCAL_ADDRESS=$(ip route get 1 | grep -oP '(?<=src ).*' | awk '{ print $1 '})
    export JVB_WS_SERVER_ID_FALLBACK="$LOCAL_ADDRESS"

    # Резолвим доменные имена в IP-адреса
    if [[ -n "$JVB_ADVERTISE_DOMAINS" ]]; then
        IFS=',' read -r -a DOMAINS <<< "$JVB_ADVERTISE_DOMAINS"
        IPS=""
        for DOMAIN in "${DOMAINS[@]}"; do
            IP=$(dig +short "$DOMAIN" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
            if [[ -n "$IP" ]]; then
                IPS="${IPS:+$IPS,}$IP"
            fi
        done
        export JVB_ADVERTISE_IPS="${IPS:-$LOCAL_ADDRESS}"
    fi
fi

# Генерация конфигурационных файлов
tpl /defaults/logging.properties > /config/logging.properties
tpl /defaults/jvb.conf > /config/jvb.conf

chown -R jvb:jitsi /config
