#!/usr/bin/with-contenv bash

if [[ -z $JVB_DISABLE_XMPP ]]; then
    if [[ -z $JVB_AUTH_PASSWORD ]]; then
        echo 'FATAL ERROR: JVB auth password must be set'
        exit 1
    fi

    OLD_JVB_AUTH_PASSWORD=passw0rd
    if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
        echo 'FATAL ERROR: JVB auth password must be changed, check the README'
        exit 1
    fi

    # Указываем Prosody как XMPP-сервер
    [ -z "${XMPP_SERVER}" ] && export XMPP_SERVER="prosody"

    # Локальный IP для ICE
    export LOCAL_ADDRESS=$(ip route get 1 | grep -oP '(?<=src ).*' | awk '{ print $1 '})
    export JVB_WS_SERVER_ID_FALLBACK="$LOCAL_ADDRESS"
fi

# Указываем публичный IP
if [[ -z "${JVB_ADVERTISE_IPS}" && ! -z "${DOCKER_HOST_ADDRESS}" ]]; then
    echo "WARNING: DOCKER_HOST_ADDRESS is deprecated, migrate to JVB_ADVERTISE_IPS"
    export JVB_ADVERTISE_IPS=${DOCKER_HOST_ADDRESS}
fi

# Генерация конфигурационных файлов
tpl /defaults/logging.properties > /config/logging.properties
tpl /defaults/jvb.conf > /config/jvb.conf

chown -R jvb:jitsi /config
