#!/usr/bin/with-contenv bash

PROSODY_CFG="/config/prosody.cfg.lua"

echo "Waiting for Prosody to start..."
while ! prosodyctl --config "$PROSODY_CFG" status | grep -q "Prosody is running"; do
    sleep 1
done

echo "Registering focus user..."
echo -e "$JICOFO_AUTH_PASSWORD\n$JICOFO_AUTH_PASSWORD" | prosodyctl --config "$PROSODY_CFG" adduser focus@${XMPP_AUTH_DOMAIN:-auth.meet.jitsi}
echo "Registering jvb user..."
echo -e "$JVB_AUTH_PASSWORD\n$JVB_AUTH_PASSWORD" | prosodyctl --config "$PROSODY_CFG" adduser ${JVB_AUTH_USER:-jvb}@${XMPP_AUTH_DOMAIN:-auth.meet.jitsi}
if [[ ! -z $JIBRI_XMPP_PASSWORD ]]; then
    echo "Registering jibri user..."
    echo -e "$JIBRI_XMPP_PASSWORD\n$JIBRI_XMPP_PASSWORD" | prosodyctl --config "$PROSODY_CFG" adduser ${JIBRI_XMPP_USER:-jibri}@${XMPP_AUTH_DOMAIN:-auth.meet.jitsi}
fi
if [[ ! -z $JIGASI_XMPP_PASSWORD ]]; then
    echo "Registering jigasi user..."
    echo -e "$JIGASI_XMPP_PASSWORD\n$JIGASI_XMPP_PASSWORD" | prosodyctl --config "$PROSODY_CFG" adduser ${JIGASI_XMPP_USER:-jigasi}@${XMPP_AUTH_DOMAIN:-auth.meet.jitsi}
fi

echo "Checking registered users after registration..."
ls -l /config/data/auth.meet.jitsi/accounts/
